[build]
  publish = "public/"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "8"
  YARN_VERSION = "1.5.1"
  YARN_FLAGS = "--pure-lockfile --verbose"

# A basic redirects rule
[[redirects]]
  from = "http://spacetime-gatsby.netlify.com/*"
  to = "http://www.heyspacetime.com/:splat"
  status = 301
